# Generated by Django 5.2.4 on 2025-09-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_conversationparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='unique_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
