# Generated by Django 5.2.4 on 2025-09-22 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_messagefile_readreceipt_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
