# Generated by Django 5.2.4 on 2025-07-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_avatar_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_on_new_message',
            field=models.BooleanField(default=True),
        ),
    ]
