# Generated by Django 5.2.4 on 2025-08-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_email_on_new_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fraud_warning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
