# Generated by Django 5.2.4 on 2025-08-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_fraud_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_verification_message',
            field=models.BooleanField(default=False),
        ),
    ]
