# Generated by Django 5.2.4 on 2025-08-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_has_seen_verification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_edited_critical_details',
            field=models.BooleanField(default=False, help_text='Tracks if the user has used their one-time edit for critical details.'),
        ),
    ]
