# Generated by Django 5.2.4 on 2025-09-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Restricted users cannot send new messages.'),
        ),
    ]
