# Generated by Django 5.2.4 on 2025-09-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_is_restricted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_restricted',
        ),
    ]
