# Generated by Django 5.2.4 on 2025-09-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_on_new_message',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_on_connection_accepted',
            field=models.BooleanField(default=True, help_text='Send an email when someone accepts your connection request.'),
        ),
    ]
