# Generated by Django 5.2.6 on 2025-09-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
